jobs:
- job: Preview
  displayName: Create Docs Preview
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        set -e -o pipefail

        mkdir dist/info -p
        export SHA=$(node -pe 'const {env}=process;env.SYSTEM_PULLREQUEST_SOURCECOMMITID || env.BUILD_SOURCEVERSION')
        echo $SHA > ./dist/info/SHA
      noRc: false
    displayName: "Write data"
  - task: PublishPipelineArtifact@1
    inputs:
      artifact: preview
      path: 'dist/info'
